### ISSUE TITLE
 Align the styles from MINT web.

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mic-web#9]

**Comment by mosoriob** [comment]
Can you align the nav bar?

![image](https://user-images.githubusercontent.com/2365990/140059943-9cb79036-2dbd-4197-8f8c-e04c7421d5ea.png)
![image](https://user-images.githubusercontent.com/2365990/140060041-8c53f9ad-7401-4903-8756-582124694dad.png)

**Comment by hvarg** [comment]
added the icon on da3985aacd75a8b65c121bd545908d259b85e4b6, do you want to match the colors or the "tab" style?

**Comment by mosoriob** [comment]
I would like to match the colors and the tab. 
My idea is that Yolanda or users don't feel that mic web is a different system that MINT-UI

**Comment by hvarg** [comment]
Now looks this way on dev
<img width="691" alt="Screen Shot 2021-11-09 at 22 00 23" src="https://user-images.githubusercontent.com/15269912/141030346-9cbb0b39-5e96-4796-b6da-7c78cb6d8215.png">
